# Generated by Django 2.2.1 on 2019-06-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('pres', 'President'), ('man', 'Manager'), ('sta', 'Staff')], default='Staff', max_length=10)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='dbrel.Employee')),
            ],
        ),
    ]
